### ISSUE TITLE
Improve logic for rendering CPC report links

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-zap-search#113]
https://zap-search.planninglabs.nyc/projects/P1980M0609

**Comment by chriswhong** [comment]
- Generate whitelist of action types that should have a CPC report link built from their ULURP number field.
- Only build a CPC report link if the action is on the whitelist.

**Comment by chriswhong** [comment]
I don't think there is a way to programmatically know whether or not a CPC report should exist for a given ULURP number, so we don't have a lot of options here.  Either they are all links and some don't work, or no links...

**Comment by chriswhong** [comment]
Received feedback via email that some dead CPC report links are causing a poor user experience.  We need a dataset of known CPC report URLS to validate against.  @CeciliaCY does this exist?

**Comment by CeciliaCY** [comment]
> Received feedback via email that some dead CPC report links are causing a poor user experience. We need a dataset of known CPC report URLS to validate against. @CeciliaCY does this exist?

Yes, there is one:
https://a030-cpc.nyc.gov/html/cpc/report.aspx?num=N%20110090a%20ZRY

num=**N 110090a ZRY**  (bold is cpc number)

**Comment by allthesignals** [comment]
> ```
2019-08-21T18:19:14.484728414Z app[web.1]: TypeError: Cannot read property 'match' of undefined
2019-08-21T18:19:14.484834675Z app[web.1]:     at getRole (/usr/src/app/routes/login.js:80:22)
2019-08-21T18:19:14.484854374Z app[web.1]:     at contacts.map.contact (/usr/src/app/routes/login.js:72:18)
2019-08-21T18:19:14.484869849Z app[web.1]:     at Array.map (&lt;anonymous&gt;)
2019-08-21T18:19:14.484882620Z app[web.1]:     at getContactForSession (/usr/src/app/routes/login.js:70:35)
2019-08-21T18:19:14.484895057Z app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
```
<sub>[View in Slack](https://nycplanning.slack.com/archives/CB4JLJXLY/p1566411697110100)</sub>
