### ISSUE TITLE
Research ZAP Search radius filter bug

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/labs-zap-search#1498]

**Comment by pratishta** [comment]
Work on this ticket is happening on this branch: [pratishta/radius-filter](https://github.com/NYCPlanning/labs-zap-search/tree/pratishta/radius-filter)

I didn't read Tyler's last comment about adding `blocks_in_radius` to `ALLOWED_FILTERS` so I spent earlier today 'figuring that out' on my own 🥸

But the main error we get from just making the above change is:

```
TypeError: strings.map is not a function
    at Object.containsAnyOf (/Users/pratishtayerakala/dcp_ae/labs-zap-search/server/dist/crm/crm.utilities.js:69:10)
    at Object.blocks_in_radius (/Users/pratishtayerakala/dcp_ae/labs-zap-search/server/dist/project/project.service.js:135:58)
```

And it's because of two things happening in the same file `project.service.ts`: 
1. We have to manually delete the blocks query attribute. The query attribute name changed from `block` to `blocks_in_radius` a [while back](https://github.com/NYCPlanning/labs-zap-search/commit/b99b256b86f99db2f834d49a3f2083f0e546d26f), but we never updated the manual deleting with the new attribute name. I updated the `QUERY_TEMPLATES` to reflect that.
2. The condition to delete that attribute doesn't really work 
```
  if (!query.block) delete query.block;
  ```
The most canonical way I found to check for an empty object seemed to be to check the length of its keys so I changed it to that.

**Comment by pratishta** [comment]
Potential solution here https://github.com/NYCPlanning/labs-zap-search/pull/1500

I worked on getting the existing radius filter to work. David updated it so that only projects in the borough of the radius filter show up. 

I'm not sure how to add or update tests for this. Having trouble getting the tests to run locally.

**Comment by pratishta** [comment]
With this current fix, there is still a bug: when the radius is very small (~25-140ft) carto doesn't pull any valid blocks and we have an empty `blocks_in_radius` list. As described in an earlier comment, we then delete this attribute from the query. But doing so makes it so that there's no radius filter at all and thus returns all projects. 

It might be worthwhile to restructure how we handle the filter:
- Keep the empty block list and force a filter with the CRM API (e.g. when radius filter is on and block list is empty, set it to [null])
- Removing the deprecated `blocks` code so that `blocks_in_radius` is the only source of truth for the blocks contained in the radius filter
-  Don't allow adjusting filters or radius size when loading

**Comment by TylerMatteo** [comment]
@pratishta I did a little more digging after our call. I have some changes that seem to solve all but one of our issues, and I think I have a path forward for the one remaining.

* The first thing I did was update `blocksWithinRadius` to return `false` instead of `{}` when `distance_from_point` and `radius_from_point` are undefined. Empty objects are truthy so passing literal `false` seemed like it might help simplify `queryProjects`
* I updated the first few lines of `queryProjects` to read:
```
    const normalizedQuery = blocks === false ? {...query} : {
      blocks_in_radius: blocks,
      ...query
    };
```
* I removed `if (!Object.keys(query.blocks_in_radius).length) delete query.blocks_in_radius;` from `generateProjectsFilterString` because it should no longer be necessary???

Now it seems to be returning all projects that match the other filters when the radius filter is off or when it's on but you haven't picked a lat/long yet. The issue I still have is that when you select a radius that returns an empty list of blocks, you get back every project that matches the other criteria. 


![Image](https://github.com/NYCPlanning/labs-zap-search/assets/9055367/644fbac7-0c4b-4a76-8e38-d6ccffdccfd8)

I noticed that when I log out the `$filter` that is send to the OData API in this scenario, it doesn't have the clause for projectbbls at all
```
(dcp_visibility eq 717170003) and (dcp_dcp_project_dcp_projectbbl_project/any()) and ((dcp_publicstatus eq 717170001) or (dcp_publicstatus eq 717170005))
```

That's because the `startsWithAnyOf` utility in `crm.utilities.ts` is mapping over an empty list of bbls, so it doesn't add anything. If we wanted to implement this correctly in the OData query, we really need that utility to always add a condition that says essentially "only give me back projects that have at least one associate project bbl, even if this list of blocks is empty". That would give us a way to filter out the "unmapped" projects.

Implementing that in OData might be tricky but I brought this up with @dhochbaum-dcp and he made a good point - if the radius filter is on with a radius selected but no blocks exist within that radius, we would _always_ expect the filter to return 0 projects. With that in mind, there may be an easier way to achieve this but "short circuiting" the query code to just return an empty search result when the blocks query to Carto returns an empty list.

**Comment by TylerMatteo** [comment]
@pratishta @dhochbaum-dcp We've firmly crossed over into actually fixing this issue so I renamed it and will carry it over into sprint J

**Comment by TylerMatteo** [comment]
Moving back to In Progress until the above bugs are resolved

**Comment by TylerMatteo** [comment]
Yes I think that is the best approach. I confirmed the code in your branch is skipping the odata request in the scenario I would expect it to. Maybe we could pair on the clean up? I have some thoughts about how we can refactor the existing code to be a little easier to follow.

**Comment by TylerMatteo** [comment]
I merged @pratishta's PR for this so the fix is testable at https://zap-staging.planninglabs.nyc/. I did some testing and seems to generally be working fine but I'd like to get another pair of eyes on it before we release. @dhochbaum-dcp can you spend some time trying to break it? I'm thinking an hour, tops.

**Comment by dhochbaum-dcp** [comment]
Seems good to me, I didn't find issues aside from the already documented bug.
